version: '3'
services:
  dns:
    build: ./dns
    image: docker_dns
    container_name: dns
    env_file:
      - .env
    volumes:
      - ./dns:/mnt/dns
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "53/udp"
    networks:
      imsnet:
        ipv4_address: ${DNS_IP}

  rtpengine:
    build: ./rtpengine
    image: docker_rtpengine
    container_name: rtpengine
    privileged: true
    env_file:
      - .env
    volumes:
      - ./rtpengine:/mnt/rtpengine
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    environment:
      - TABLE=0
      - INTERFACE=${RTPENGINE_IP}
      - LISTEN_NG=${RTPENGINE_IP}:2223
      - PIDFILE=/run/ngcp-rtpengine-daemon.pid
      - PORT_MAX=50000
      - PORT_MIN=49000
      - NO_FALLBACK=no
      - TOS=184
    expose:
      - "2223/udp"
      - "49000-50000/udp"
    ports:
      - "2223:2223/udp"
      - "49000-50000:49000-50000/udp"
    networks:
      imsnet:
        ipv4_address: ${RTPENGINE_IP}
    depends_on:
      dns:
        condition: service_started

  mysql:
    build: ./mysql
    image: docker_mysql
    container_name: mysql
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3306/tcp"
    networks:
      imsnet:
        ipv4_address: ${MYSQL_IP}
    depends_on:
      dns:
        condition: service_started

  fhoss:
    build: ./fhoss
    image: docker_fhoss
    container_name: fhoss
    dns: ${DNS_IP}
    volumes:
      - ./fhoss:/mnt/fhoss
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      dns:
        condition: service_started
      mysql:
        condition: service_started
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3869/udp"
      - "3869/tcp"
      - "3870/udp"
      - "3870/tcp"
    ports:
      - "8080:8080/tcp"
    networks:
      imsnet:
        ipv4_address: ${FHOSS_IP}

  icscf:
    image: kamailio
    container_name: icscf
    dns: ${DNS_IP}
    volumes:
      - ./icscf:/mnt/icscf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=icscf-1
    depends_on:
      dns:
        condition: service_started
      mysql:
        condition: service_started
      fhoss:
        condition: service_started
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3869/udp"
      - "3869/tcp"
      - "4060/udp"
      - "4060/tcp"
    networks:
      imsnet:
        ipv4_address: ${ICSCF_IP}

  scscf:
    image: kamailio
    container_name: scscf
    dns: ${DNS_IP}
    volumes:
      - ./scscf:/mnt/scscf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=scscf-1
    depends_on:
      dns:
        condition: service_started
      mysql:
        condition: service_started
      fhoss:
        condition: service_started
    expose:
      - "3870/udp"
      - "3870/tcp"
      - "6060/udp"
      - "6060/tcp"
    networks:
      imsnet:
        ipv4_address: ${SCSCF_IP}

  pcscf:
    image: kamailio
    container_name: pcscf
    dns: ${DNS_IP}
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pcscf:/mnt/pcscf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=pcscf-1
    depends_on:
      dns:
        condition: service_started
      mysql:
        condition: service_started
      fhoss:
        condition: service_started
      rtpengine:
        condition: service_started
      icscf:
        condition: service_started
      scscf:
        condition: service_started
    expose:
      - "3871/udp"
      - "3871/tcp"
      - "5060/tcp"
      - "5060/udp"
      - "5100-5120/tcp"
      - "5100-5120/udp"
      - "6100-6120/tcp"
      - "6100-6120/udp"
    ports:
    #   - "3871:3871/udp"
    #   - "3871:3871/tcp"
    #   - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5100-5120:5100-5120/tcp"
    #   - "5100-5120:5100-5120/udp"
    #   - "6100-6120:6100-6120/tcp"
    #   - "6100-6120:6100-6120/udp"
    networks:
      imsnet:
        ipv4_address: ${PCSCF_IP}

  opensips:
    build: ./opensips
    image: opensips
    container_name: opensips
    dns: ${DNS_IP}
    env_file:
      - .env
    depends_on:
      dns:
        condition: service_started
      mysql:
        condition: service_started
      fhoss:
        condition: service_started
      rtpengine:
        condition: service_started
      icscf:
        condition: service_started
      scscf:
        condition: service_started
    volumes:
      - ./opensips:/mnt/opensips
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "5065/udp"
    networks:
      imsnet:
        ipv4_address: ${PRESENCE_IP}

volumes:
  dbdata: {}

networks:
  imsnet:
    ipam:
      config:
        - subnet: ${TEST_NETWORK}